Navigationbar headline
DavyKn/my_portfolio pull request #1
Opened 2022-03-22 20:18 UTC by DavyKn

Added Navigation bar ,headline and CSS styling

2022-03-22 21:29 UTC, rotimiazeez requested changes
# Hi @DavyKn 👋, 
## Good job so far!👍👍
### Summary 👏
- No linter errors ✔
- Good commit message 👍
- Descriptive PR message😊
- Good Readme 🚀
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 21:29 UTC, rotimiazeez commented on index.html
> +  </section>
- [ ] Kindly make the sections has the proper background image as seen in the original design 👍
Your design | Figma design
![screenshot (43)](https://user-images.githubusercontent.com/44624138/159578695-3db72ba2-0870-4aee-8e79-a4dd83629233.png) | ![screenshot (42)](https://user-images.githubusercontent.com/44624138/159578717-52dd57ce-8f3c-418b-b881-f8b312b3519e.png)

2022-03-22 21:47 UTC, DavyKn commented
Thank you for the review as you have mentioned the changes are optional,
kindly approve the project so that I can move to the next one,On the next
one will consider every single detail, Thank you

On Wed, Mar 23, 2022 at 12:29 AM Azeez Rotimi Arigbabuwo <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> Hi @DavyKn <https://github.com/DavyKn> 👋, Good job so far!👍👍 Summary 👏
>
>    - No linter errors ✔
>    - Good commit message 👍
>    - Descriptive PR message😊
>    - Good Readme 🚀
>    There are some issues that you still need to work on to go to the next
>    project but you are almost there!
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/DavyKn/my_portfolio/pull/1#discussion_r832641679>:
>
> > +  <header>
>
> +    <nav class="navbar">
>
> +      <a class="logo" href="#">Davis Nyale</a>
>
> +      <img class="menu" src="./assets/Menu.png" alt="menu">
>
> +    </nav>
>
> +  </header>
>
> +  <section class="headline">
>
> +    <h1 class="myname">Davis Nyale</h1>
>
> +    <h2 class="subtitle">Software Developer</h2>
>
> +    <p class="myinfo">I can help you build a product , feature or website Look through some of my work
>
> +      and experience! If you like what you see and have a project you need coded,  don’t hestiate to contact me.</p>
>
> +  </section>
>
> +  <section class="languages_container">
>
> +    <div class="language">
>
> +      <h6>Languages</h6>
>
> +      <ul>
>
> +        <li>Javascript</li>
>
> +        <li>Ruby</li>
>
> +        <li>Html</li>
>
> +        <li>CSS</li>
>
> +      </ul>
>
> +    </div>
>
> +    <div class="frameworks">
>
> +      <h6>Frameworks</h6>
>
> +      <ul>
>
> +        <li>Bootstrap</li>
>
> +        <li>Ruby on Rails</li>
>
> +        <li>RS spec</li>
>
> +        <li>Capy Bara</li>
>
> +        <li>Selenium</li>
>
> +      </ul>
>
> +    </div>
>
> +    <div class="skills">
>
> +      <h6>Skills</h6>
>
> +      <ul>
>
> +        <li>CodeKit</li>
>
> +        <li>GitHub</li>
>
> +        <li>Codepen</li>
>
> +        <li>Gitlab</li>
>
> +        <li>Terminal</li>
>
> +      </ul>
>
> +    </div>
>
> +  </section>
>
> +  <section class="social_media_container">
>
> +    <ul class="social_media">
>
> +      <li><a href="#"><img src="./assets/GitHub.png" alt="github"></a></li>
>
> +      <li><a href="#"><img src="./assets/Linkedin.png" alt="linkedin"></a></li>
>
> +      <li><a href="#"><img src="./assets/angellist1.png" alt="angellist"></a></li>
>
> +      <li><a href="#"><img src="./assets/twitter.png" alt="twitter"></a></li>
>
> +      <li><a href="#"><img src="./assets/medium.png" alt="medium"></a></li>
>
> +    </ul>
>
> +  </section>
>
>
>
>    - Kindly make the sections has the proper background image as seen in
>    the original design 👍
>    Your design | Figma design
>    [image: screenshot (43)]
>    <https://user-images.githubusercontent.com/44624138/159578695-3db72ba2-0870-4aee-8e79-a4dd83629233.png>
>    | [image: screenshot (42)]
>    <https://user-images.githubusercontent.com/44624138/159578717-52dd57ce-8f3c-418b-b881-f8b312b3519e.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DavyKn/my_portfolio/pull/1#pullrequestreview-917908775>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH65FG6BAO6KB7GHSM2PDULVBI3UZANCNFSM5RL6ZMAA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-22 22:34 UTC, rotimiazeez commented
Hi @DavyKn,
Please note that it is part of the requirement to make sure your design match that of the Figma template you chose 💯. Kindly implement the changes and you'll surely be approved by the next reviewer 😉.

2022-03-22 23:32 UTC, Gambit142 requested changes
Hi @DavyKn 👋, 

Great attempt trying to implement the background images requested by a previous reviewer 👏 
You've done well attempting to make some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 23:32 UTC, Gambit142 commented on index.html
> +  </section>
- [ ] One of the project requirements state that your design should be identical to that of the Figma template you chose. This was highlighted by the previous reviewer. You can download the background picture from Figma using the following steps:
- On the left side of the design, you would see a dropdown for portfolio background shapes mobile. Click on it.

![image](https://user-images.githubusercontent.com/77106962/159592082-0bd492b3-f465-43e8-a24f-4bb8a9818060.png)

- On the inspect panel pane to the right, you would see the export sub-heading, click on it and you would see this

![image](https://user-images.githubusercontent.com/77106962/159592372-a26cb971-5df1-4614-a59f-1f3261331969.png)

- Next thing would be to change the file extension to `png` or `jpg` but I would recommend `png`. You can decide to change the size also if you wish.

![image](https://user-images.githubusercontent.com/77106962/159592669-7659d621-0792-4988-8a86-7b069f5f6b5c.png)

- The last step is to click the export button and then add the picture downloaded to your asset folder in the project. I would also recommend that you use the image downloaded as the `background-image` of the `body` HTML tag because it is the image for the whole mobile view. 👍

2022-03-23 11:55 UTC, Davidosky007 reviewed
Hello @DavyKn  👋,

_This is an additional review as a result of the second opinion request._

- Well done working hard on this project and implementing some of the requested changes👍 
- Kindly note that one of the learning objectives for this milestone is to Understand how to parse a Figma design to create a UI. so therefore your design should look like what we have in the figma template Your design background image is slightly different from the Figma design. Please follow the instruction on how to copy an image from Figma design by @Gambit142 
- Below is a screenshot of what's missing in your design  
![image](https://user-images.githubusercontent.com/52497246/159692364-10ecae0d-a698-4573-a9c3-0d6514ca153a.png)


Kindly fix this issue and submit it for another review 
Please ask for another review in your Dashboard and the next Code Reviewer will review it accordingly  :)

Keep rocking 🚀!

2022-03-23 15:04 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @DavyKn👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 15:06 UTC, merged

2022-03-23 15:07 UTC, DavyKn commented
merged successfully